### ISSUE TITLE
Magic numbers when precomputing frequencySteps

### ISSUE THREAD

**Issue by wgj** [sabeechen/FixedJamboxSequencer#1]
When [precomputing `frequencySteps[]`](https://github.com/sabeechen/FixedJamboxSequencer/blob/master/JamboxSequencer.ino#L162), I'm unsure why `noteFrequencies[]` are multiplied by `PI` and `2`. 

For instance, I'm not sure whether the multiplication is for the sinusoidal wave of a note or the analog/digital conversion for potentiometers minutes. Or whether not using `PI2` is meant to demonstrate something important, or an implicit workaround for finicky MCUs.

A good explanation might be out of scope, so a terse explanation with proper nouns that can be looked up elsewhere, like Wikipedia or another reference, would be fine.

**Comment by sabeechen** [comment]
If "f" is frequency in Hz and "t" is time in seconds, then `sin(2 * pi * f *t)` describes a wave of frequency f.  Given a SAMPLE_RATE_HZ, then the "n"th sample of that waveform would be` sin(2 * pi * f * (n/SAMPLE_RATE))`.  Keeping track of `step = (2 * pi * f)/SAMPLE_RATE` lets you compute sin(n * step) instead, which is a little more efficient.  Every cycle counts for making the samples because the ESP32 isn't super fast.

**Comment by sabeechen** [comment]
Oh also, sin(x) expects x to be in [radians](https://en.wikipedia.org/wiki/Radian), and `2 * PI` is special in that regard because it represents one full "rotation" around the circle (eg `sin(x) == sin(x + 2*PI*n)` when n is an integer).  An example might help, here is the graph of a [100Hz wave](https://www.google.com/search?q=graph+of+sin%28100+*+t+*+2+*+PI%29).
